name: kassoua
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Composants & UI
  google_fonts: ^6.1.0 
  iconsax: ^0.0.8
  lucide_icons: ^0.257.0
  carousel_slider: ^5.1.1
  font_awesome_flutter: ^10.8.0
  flutter_multi_formatter: ^2.13.7



  # Formulaire & Saisie
  intl_phone_field: ^3.2.0
  email_validator: ^3.0.0
  country_picker: ^2.0.27
  image_picker: ^1.0.4

  # Services Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  # firebase_messaging: ^15.2.7
  http: ^1.4.0


  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # Local Storage & Database
  shared_preferences: ^2.5.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Gestion d'État
  get: ^4.6.5
  provider: ^6.1.2

  # Reseau & connectivité
  connectivity_plus: ^5.0.2

  # Internationalization & Formatting
  intl: ^0.19.0

  # Development & Debug Tools
  logger: ^2.0.2
  panara_dialogs: ^0.1.5
  skeletonizer: ^1.4.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding-image1.png
    - assets/images/user.png
    - assets/images/icons/icons-google.png
    - assets/images/icons/warning.png
    - assets/images/icons/tick-circle.png
    - assets/images/icons/refresh-arrow-02.png
    - assets/images/logos/app_logo.png


# Police

    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-Thin.ttf
