name: kassoua
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Composants & UI
  google_fonts: ^6.1.0 
  iconsax: ^0.0.8
  lucide_icons: ^0.257.0
  carousel_slider: ^5.1.1

  # Formulaire & Saisie
  intl_phone_field: ^3.2.0
  email_validator: ^3.0.0
  country_picker: ^2.0.27
  image_picker: ^1.0.4

  # Services Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # Local Storage & Database
  shared_preferences: ^2.5.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

  # Gestion d'État
  get: ^4.6.5
  provider: ^6.1.2

  # Reseau & connectivité
  connectivity_plus: ^5.0.2

  # Internationalization & Formatting
  intl: ^0.19.0

  # Development & Debug Tools
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding-image1.png
    - assets/images/user.png
    - assets/images/icons/icons-google.png


# Police

    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-Thin.ttf
